# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  deploystage:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo ${{ github.event_name }}
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        # Name of the Azure Web App
        app-name: tonkatsu-github-training
        # Applies to Web App only: Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.staging_slot }}
        # Enter an existing Slot other than the Production slot
        slot-name: staging
    
                
  deployprod:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo ${{ github.event_name }}
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      if: ${{ github.event == 'push' }}
      with:
        # Name of the Azure Web App
        app-name: tonkatsu-github-training
        # Applies to Web App only: Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.production_slot }}
    
